<?php

namespace liuxy\frontend\assets;

/**
 * core asset bundle.
 */
class BaseAsset extends AbstractAsset {

    /**
     * @inheritdoc
     */
    protected $plugin_css = [
        'css/core.min.css'
    ];

    protected $plugin_js = [
        'scripts/core.min.js'
    ];

    /**
     * @inheritdoc
     */
    protected $plugin_depends = [
        'liuxy\frontend\assets\IE9Asset'
    ];

    public function init()
    {
        $this->sourcePath = '@liuxy/themes/frontend/'.\Yii::$app->getView()->theme->template;
        parent::init(); // TODO: Change the autogenerated stub
    }

}
